window.onload = (event) => {
    console.log("Page finsihed");
    const board1 = document.getElementById("board");
    const div0 = board1.getElementsByTagName("div")[0];
    div0.className = "square";
    const div1 = board1.getElementsByTagName("div")[1];
    div1.className = "square";
    const div2 = board1.getElementsByTagName("div")[2];
    div2.className = "square";
    const div3 = board1.getElementsByTagName("div")[3];
    div3.className = "square";
    const div4 = board1.getElementsByTagName("div")[4];
    div4.className = "square";
    const div5 = board1.getElementsByTagName("div")[5];
    div5.className = "square";
    const div6 = board1.getElementsByTagName("div")[6];
    div6.className = "square";
    const div7 = board1.getElementsByTagName("div")[7];
    div7.className = "square";
    const div8 = board1.getElementsByTagName("div")[8];
    div8.className = "square";
};
  /*  //console.log("Onload succesful!");
    const board1 = document.getElementById("board");
    const div0 = board1.getElementsByTagName("div")[0];
    div0.className = "square";
    const div1 = board1.getElementsByTagName("div")[1];
    div1.className = "square";
    const div2 = board1.getElementsByTagName("div")[2];
    div2.className = "square";
    const div3 = board1.getElementsByTagName("div")[3];
    div3.className = "square";
    const div4 = board1.getElementsByTagName("div")[4];
    div4.className = "square";
    const div5 = board1.getElementsByTagName("div")[5];
    div5.className = "square";
    const div6 = board1.getElementsByTagName("div")[6];
    div6.className = "square";
    const div7 = board1.getElementsByTagName("div")[7];
    div7.className = "square";
    const div8 = board1.getElementsByTagName("div")[8];
    div8.className = "square";*/